---
title: "Exploraci贸n"
author: "Diabb Zegpi D."
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(tidyverse)
library(tidymodels)
library(lubridate)
library(here)

# tidymodels_prefer()
theme_set(theme_minimal())
construccion_clean <- readRDS(here("Data", "construccion_clean.rds")) |> 
  filter(year(fecha) <= 2020)
```


```{r}
construccion_clean |> 
  # filter(accion == "Besalco S.A. Ord") |> 
  select(fecha, metrica = ebitda, accion) |> 
  mutate(year = year(fecha)) |> 
  group_by(accion) |> 
  mutate(metrica_rolling = (metrica + lag(metrica) + lag(metrica, 2) + lag(metrica, 3)) / 4) |> 
  ggplot(aes(fecha)) +
  geom_line(aes(y = metrica), color = "red") +
  geom_line(aes(y = metrica_rolling), color = "black") +
  facet_wrap(~accion, scales = "free")


metrica = "capital_trabajo"
metrica2 = "utilidad_neta"

construccion_clean |> 
  # filter(accion == "Besalco S.A. Ord") |> 
  select(fecha, metrica = {{metrica}}, metrica2 = {{metrica2}}, accion) |> 
  mutate(year = year(fecha)) |> 
  group_by(accion) |> 
  mutate(metrica_rolling = (metrica + lag(metrica) + lag(metrica, 2) + lag(metrica, 3)) / 4,
         metrica2_rolling = (metrica2 + lag(metrica2) + lag(metrica2, 2) + lag(metrica2, 3)) / 4) |> 
  ggplot(aes(x = metrica_rolling, y = metrica2_rolling)) +
  geom_point(color = "black")  +
  labs(x = paste(metrica, "m贸vil"),
       y = paste(metrica2, "m贸vil")) +
  geom_smooth()
  # facet_wrap(~accion, scales = "free")
```



```{r}
crecimiento <- construccion_clean |> 
  mutate(year = year(fecha)) |> 
  group_by(accion, year) |> 
  arrange(year) |> 
  summarise(ventas_anuales = sum(ingreso_neto), 
            .groups = "drop_last") |> 
  summarise(oportunidades_crec = log(
    ventas_anuales / dplyr::lag(ventas_anuales)
  ),
  .groups = "drop") |> 
  mutate(oportunidades_crec = if_else(
    is.na(oportunidades_crec), 0, oportunidades_crec
  ))

crecimiento <- construccion_clean |> 
  mutate(year = year(fecha)) |> 
  distinct(accion, year) |> 
  mutate(oportunidades_crec = crecimiento$oportunidades_crec)

corr_data <- construccion_clean |> 
  mutate(year = year(fecha)) |> 
  left_join(crecimiento, 
            by = c("accion", "year")) |> 
  transmute(
    endeudamiento_cp = pasivo_corriente / activo_total,
    tamano_empresa = log(activo_total),
    tangibilidad_act = activo_tangible / activo_total,
    oportunidades_crec,
    margen_bruto = resultado_bruto / ingreso_neto,
    p_vl,
    ebitda,
    ciclo_operativo,
    CT_neto = capital_trabajo / activo_total,
    CT_neto_2 = CT_neto ^ 2,
    ROA = utilidad_neta / activo_total,
    ROE = utilidad_neta / (activo_total - pasivo_total)
  ) |> 
  na.omit() |> 
  corrr::correlate(diagonal = 1) |> 
  corrr::shave(upper = FALSE) |> 
  pivot_longer(
    cols = -term,
    names_to = "colname",
    values_to = "corr"
  ) |> 
  mutate(
    rowname = fct_inorder(term),
    colname = fct_inorder(colname),
    label = if_else(is.na(corr), "", sprintf("%1.2f", corr))
  )

ggplot(corr_data, aes(rowname, fct_rev(colname), 
                      fill = corr)) +
  geom_tile() +
  geom_text(aes(
    label = label,
    color = abs(corr) < .75
  )) +
  coord_fixed(expand = FALSE) +
  scale_color_manual(
    values = c("white", "black"),
    guide = "none"
  ) +
  scale_fill_distiller(
    palette = "PuOr",
    na.value = "white",
    direction = 1,
    limits = c(-1, 1),
    name = "Correlaci贸n\nde Pearson"
  ) +
  labs(x = NULL, y = NULL) +
  theme(text = element_text(size = 16),
        panel.border = element_rect(color = NA, fill = NA),
        legend.position = c(.85, .8),
        axis.text.x = element_text(angle = 90),
        axis.ticks = element_blank(),
        panel.grid = element_blank())

```

```{r}
construccion_clean |> 
  mutate(ROA = utilidad_neta / activo_total,
         ROE = utilidad_neta / (activo_total - pasivo_total)) |> 
  ggplot(aes(capital_trabajo, ROA)) +
  geom_point(alpha = .6, size = 2) 
```

